Move to requests and drop Python 2 support
MTG/freesound-python pull request #32
Opened 2022-09-26 21:42 UTC by Bomme

This PR updates the client and brings in [requests](https://requests.readthedocs.io/en/latest/) for extra ease of use.
My main motivation to use requests was to get connection pooling when doing multiple requests to the API.
The only breaking change in the API of the client should be that the `retrieve` functions no longer accept a `reporthook` parameter.

With requests users can now easily extend/modify the way how requests are done by interacting directly with the session object of the client.
For example, adding proxies:
```python
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
client.session.proxies.update(proxies)
```

or adding [rate limiting](https://github.com/JWCook/requests-ratelimiter):
```python
from requests_ratelimiter import LimiterSession

# Apply a rate-limit (59 requests per minute) to all requests
client.session = LimiterSession(per_minute=59)
```

2022-09-27 08:21 UTC, ffont requested changes
Thanks @Bomme for your contributions, this is a great PR!

I just left a couple of comments with minor issues. Apart from that, I think it would be nice to add instructions in the README to install the Python2 compatible version (which would be using `pip install git+https://github.com/MTG/freesound-python@py2`), and adding a note about the new functionalities enabled because of using `requests` that you mention in the PR description (limiting and proxies).

2022-09-27 08:21 UTC, ffont commented on freesound.py
> +from requests import Session, Request, JSONDecodeError, HTTPError
I seem to be having issues with this line because `JSONDecodeError` cannot be imported from `requests`. My version of `requests` is between 2.0 and 3.0 as instructed, and using python 3.9. If I import the failing class like `from json.decoder import JSONDecodeError`, then it works. Maybe it would be worth to make that change or better understand if the version of `requests`/`python` should be specified in some other way for the import to work.

2022-09-27 08:21 UTC, ffont commented on freesound.py
> +    def retrieve(url, client, path):
In order to keep compatibility, you might want to still add `reporthook` in the function signature, and if it is ever used then maybe log a message on screen mentioning that in does not work with version >=X of `freesound-python`. Also add a note in the docstring about that. Also maybe we could give a pointer about how to implement something similar using requests.

2022-09-27 08:21 UTC, ffont commented on setup.py
> +      version='2.0',
maybe instead of 2.0 I'd name it 1.1. There are a number of relevant open issues that would be nice addressing before advancing to the next "major release".

2022-11-04 15:06 UTC, Bomme commented
I updated this PR and included some examples in the README.
(closes #24)

2022-11-08 12:40 UTC, ffont approved these changes

2022-11-08 12:40 UTC, merged